# ==========================================
# CONFIGURAÇÃO DO POSTGRESQL (NUVEM - SUPABASE)
# ==========================================

# URL do Pooler de Conexão (IPv4) na porta 6543

spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/horus_db

# Seu usuário agora OBRIGATORIAMENTE precisa do ponto e o ID do projeto

spring.datasource.username=postgres.rfvmxztntwczhevtvjvj
# spring.datasource.username=postgres

# Sua senha real sem colchetes

spring.datasource.password=pshorus2026
# spring.datasource.password=kauan

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Avisa o Java para usar a porta do Render, ou a 8080 se estiver no localhost
server.port=${PORT:8080}

logging.level.org.springframework.security=DEBUG